color: null
description: null
fieldLayouts:
  89b3b440-41e5-48c1-b298-7c619edf0daa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-06T16:10:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f9b31aa-bad9-42c1-a7ce-524db2e5e0f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:12:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b145a04-4bbe-4caa-be93-fea2bb0e0783 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16270621-6c36-4cdd-a0a7-1ef1bfa76fbd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 10c54570-feff-4b36-af22-30c309e6bd15
        userCondition: null
handle: image
hasTitleField: true
icon: null
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
