color: lime
description: null
fieldLayouts:
  5d4a9359-ec8b-430e-bad0-e3dbb1b3b4f1:
    cardThumbAlignment: end
    generatedFields:
      -
        handle: ''
        name: ''
        template: ''
        uid: dccd0033-ee6a-4e11-9a47-309fc9174fb0
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-06T16:01:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b66e8bc4-55e2-4132-849c-7b9f608fa1c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:12:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0840f648-5b6d-422b-ad96-bcaa66bc62d0 # Text
            handle: summary
            includeInCards: false
            instructions: 'Summary of the post.'
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb61b5a7-a602-4aae-a861-1f76f4630a55
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:12:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b145a04-4bbe-4caa-be93-fea2bb0e0783 # Image
            handle: featureImage
            includeInCards: false
            instructions: null
            label: 'Feature Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46845a5d-39e0-4661-b89c-dd450b0550f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:12:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 161cb289-056b-4e4b-828a-7065aef7acac # Post Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 744bfdda-6f50-42c3-b6ae-1b34548d04ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:12:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 871fe55d-5f99-4c5e-ab10-5cd8b0be8143 # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca536443-c84e-4dcf-a1bc-87b2c6141d49
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd7e867f-80a7-4746-9949-74e4f038ffd6
        userCondition: null
handle: post
hasTitleField: true
icon: file-lines
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
