color: null
description: null
fieldLayouts:
  1f504ac7-236f-42c7-a97a-901e440e1920:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-06T16:09:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9c43b49-b278-47e8-9c92-6b431123e08e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-06T16:11:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0840f648-5b6d-422b-ad96-bcaa66bc62d0 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b29b2d45-0188-42ec-a70c-afae716eb6de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c54ca410-4bb2-4682-98da-e912f499e2c8
        userCondition: null
handle: text
hasTitleField: true
icon: null
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
