defaultPlacement: end
fieldLayouts:
  c5f099a5-37cf-4f26-93a9-cde00ee0a9bc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-06T16:00:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c752eccb-c344-42be-bdcd-1885bfcd9d92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7c2a111-cea8-4b16-9860-1c638426188f
        userCondition: null
handle: topics
name: Topics
siteSettings:
  378112d0-a712-4ff2-87e4-92f5ac432688: # Jack Doyle
    hasUrls: true
    template: blog/_topic
    uriFormat: 'blog/topic/{slug}'
structure:
  maxLevels: 1
  uid: 45c1eb91-707c-4455-a4a3-0dacf505e861
