columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  createButtonLabel: 'Add block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 756d0cfb-c8e8-4367-98c3-f821f12b119f # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2fd64f3b-116f-4158-a643-487417f963a6 # Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
