defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 453810de-f8ae-4caa-a73f-2976cc9cc55c # Gallery meta
handle: peopleSingle
maxAuthors: 1
name: 'People Single'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  378112d0-a712-4ff2-87e4-92f5ac432688: # Jack Doyle
    enabledByDefault: true
    hasUrls: true
    template: gallery.twig
    uriFormat: people
type: single
